### ISSUE TITLE
Error if Printful variant doesn't have an attribute

### ISSUE THREAD

**Issue by scottsawyer** [graber-1/commerce_printful#3]
Some Printful products do not contain every attribute.  Example, a hat comes in only one size, so the size attribute is not included in the API.  ProductIntegrator expects each attribute in the schema to exist, and throws an error when importing such a product.  I fixed in my dev branch around line 311 of /src/Service/ProductIntegrator.php:

```
if (isset($variant_parameters[$attribute])) {
...
}
```

Once I get everything synced up, I can submit a pull request, but it's going to be a bit.

**Comment by graber-1** [comment]
I added you as a collaborator so it's easier for you to create PRs on this repo directly. I could commit this change on behalf of you but I'd need an email to do it.

**Comment by graber-1** [comment]
Ok, fixed that myself after all.
