### ISSUE TITLE
API Key stored in config may be a problem

### ISSUE THREAD

**Issue by scottsawyer** [graber-1/commerce_printful#6]
With the Printful api keys stored in config, there is a high probability of making it into a repo somewhere.  As an alternative, potentially use the [Key](https://www.drupal.org/project/key) module to avoid API keys getting exposed.

**Comment by graber-1** [comment]
Yes, but I don't see any other solution at the moment, adding a dependency doesn't seem like the good way to go, developers need to keep that in mind, we can advise in the docs.

I found a good solution for that: https://drupal.stackexchange.com/questions/185536/exclude-configuration-from-import-export - First answer by Berdir.

**Comment by scottsawyer** [comment]
Yeah, I see not wanting to add a dependency, though I've seen other modules with dependencies on Key ( such as Stripe API ).  Maybe a future feature could add support for Key if it's installed.  I typically store api keys in settings.local.php or outside of doc root anyway.
